"""add key to tea, add type model

Revision ID: 06de10231c1f
Revises: 94ecd876979b
Create Date: 2020-05-19 14:11:51.283346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06de10231c1f'
down_revision = '94ecd876979b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_type'), 'type', ['type'], unique=True)
    op.add_column('tea', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tea', 'type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tea', type_='foreignkey')
    op.drop_column('tea', 'type_id')
    op.drop_index(op.f('ix_type_type'), table_name='type')
    op.drop_table('type')
    # ### end Alembic commands ###
