"""empty message

Revision ID: 76b4addff120
Revises: 06de10231c1f
Create Date: 2020-05-22 12:23:02.562069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b4addff120'
down_revision = '06de10231c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea', sa.Column('water_temp', sa.Integer(), nullable=True))
    op.add_column('tea', sa.Column('water_time', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tea', 'type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tea', type_='foreignkey')
    op.drop_column('tea', 'water_time')
    op.drop_column('tea', 'water_temp')
    # ### end Alembic commands ###
