"""empty message

Revision ID: 94ecd876979b
Revises: 8b691a0dc0b2
Create Date: 2020-05-03 16:35:19.865849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ecd876979b'
down_revision = '8b691a0dc0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea', sa.Column('description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tea', 'description')
    # ### end Alembic commands ###
